#!/bin/bash
FOLDER="$1"
FILE="$2"

GOOGLE_DRIVE_FOLDER="0B5HYz9--YFuiMkFKclBXMnZ4SXM"

EVERNOTE_NOTEBOOK="scans"

DATE_TIME=$(date "+%Y%m%d%H%M%S%N")

EXTENSION="${FILE##*.}"

BASE_FILENAME="${FILE%.*}"

NEW_FILE="${DATE_TIME}.${EXTENSION}"

sleep 120

mv $FOLDER/$FILE $FOLDER/${NEW_FILE}

chmod 0664 ${FOLDER}/${NEW_FILE}

gdrive upload --parent ${GOOGLE_DRIVE_FOLDER} ${FOLDER}/${NEW_FILE}

RC=$?

if [[ "$RC" -eq "0" ]] ; then

   geeknote create --title "${NEW_FILE} was ${FILE}" --content "${NEW_FILE} was ${FILE}" --resource ${FOLDER}/${NEW_FILE}

fi

if [[ "$RC" -eq "0" ]] ; then

   mv ${FOLDER}/${NEW_FILE} /media/bignas/docs/scans 

fi
